{
  "services": [
    {
      "type": "web",
      "name": "redis-rate-limiter",
      "env": "node",
      "region": "oregon",
      "plan": "free",
      "buildCommand": "npm install && cd client && npm install --include=dev && npm run build",
      "startCommand": "npm start",
      "healthCheckPath": "/api/resource",
      "envVars": [
        {
          "key": "NODE_ENV",
          "value": "production"
        }
      ]
    }
  ]
}
